// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package web

import (
	"time"

	"github.com/99designs/gqlgen/graphql"
)

type Mutation struct {
}

type Query struct {
}

type ShortURLFilter struct {
	SearchTerm              *string  `json:"searchTerm,omitempty"`
	Tags                    []string `json:"tags,omitempty"`
	TagsMode                *string  `json:"tagsMode,omitempty"`
	Group                   *string  `json:"group,omitempty"`
	Domain                  *string  `json:"domain,omitempty"`
	OrderBy                 *string  `json:"orderBy,omitempty"`
	StartDate               *string  `json:"startDate,omitempty"`
	EndDate                 *string  `json:"endDate,omitempty"`
	ExcludeMaxVisitsReached *bool    `json:"excludeMaxVisitsReached,omitempty"`
	ExcludePastValidUntil   *bool    `json:"excludePastValidUntil,omitempty"`
	Page                    *int     `json:"page,omitempty"`
	ItemsPerPage            *int     `json:"itemsPerPage,omitempty"`
}

type StatsScope struct {
	ShortCode *string `json:"shortCode,omitempty"`
	Domain    *string `json:"domain,omitempty"`
	Tag       *string `json:"tag,omitempty"`
	Orphan    *bool   `json:"orphan,omitempty"`
	StartDate *string `json:"startDate,omitempty"`
	EndDate   *string `json:"endDate,omitempty"`
}

// Omitted fields stay unchanged. Explicit null clears optional fields.
type UpdateShortURLInput struct {
	LongURL        graphql.Omittable[*string]    `json:"longUrl,omitempty"`
	Title          graphql.Omittable[*string]    `json:"title,omitempty"`
	Tags           graphql.Omittable[[]string]   `json:"tags,omitempty"`
	Group          graphql.Omittable[*string]    `json:"group,omitempty"`
	MaxVisits      graphql.Omittable[*int64]     `json:"maxVisits,omitempty"`
	ValidSince     graphql.Omittable[*time.Time] `json:"validSince,omitempty"`
	ValidUntil     graphql.Omittable[*time.Time] `json:"validUntil,omitempty"`
	ForwardQuery   graphql.Omittable[*bool]      `json:"forwardQuery,omitempty"`
	Crawlable      graphql.Omittable[*bool]      `json:"crawlable,omitempty"`
	RedirectStatus graphql.Omittable[*int]       `json:"redirectStatus,omitempty"`
}

type VisitFilter struct {
	StartDate    *string `json:"startDate,omitempty"`
	EndDate      *string `json:"endDate,omitempty"`
	ExcludeBots  *bool   `json:"excludeBots,omitempty"`
	Page         *int    `json:"page,omitempty"`
	ItemsPerPage *int    `json:"itemsPerPage,omitempty"`
}
